services:
  certs-generator:
    image: alpine
    entrypoint: /bin/sh -c "apk add --no-cache openssl && /usr/local/bin/generate-certs.sh"
    volumes:
      - ssl-certs:/etc/ssl/certs
      - ./scripts/generate-certs.sh:/usr/local/bin/generate-certs.sh:ro
    restart: "no"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9000:9000"
    environment:
      RUST_LOG: "info"
      RUN_ENV: "production"
    volumes:
      - ssl-certs:/etc/ssl/certs
    depends_on:
      - certs-generator

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "443:443"
    environment:
      - SERVER_NAME=127.0.0.1
    depends_on:
      - server
    volumes:
      - ssl-certs:/etc/ssl/certs

volumes:
  ssl-certs:
