services:
  cert-checker:
    image: alpine
    entrypoint: |
      sh -c '
      if [ ! -f ./certs/cert.pem ] || [ ! -f ./certs/key.pem ]; then
        echo "ERROR: Missing SSL certificates!"
        echo "Please create certs directory with cert.pem and key.pem files"
        echo "Use generate-certs.sh script to generate self-signed certificates"
        echo "Exiting..."
        exit 1
      fi
      '
    volumes:
      - ./certs:/certs
    restart: "no"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9000:9000"
    environment:
      RUN_ENV: "production"
    volumes:
        - ./certs:/etc/ssl/certs
    depends_on:
      cert-checker:
        condition: service_completed_successfully
    restart: always

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "443:443"
    depends_on:
      server:
        condition: service_started
    volumes:
        - ./certs:/etc/ssl/certs
    restart: always
