services:
  cert-checker:
    image: alpine
    user: ${CONTAINER_USER:-nobody}
    entrypoint: |
      sh -c '
      if [ ! -f /etc/ssl/${CERT_MOUNT:-pastepoint}/cert.pem ] || [ ! -f /etc/ssl/${CERT_MOUNT:-pastepoint}/key.pem ]; then
        echo "ERROR: Missing SSL certificates!"
        echo "Please create ${CERT_PATH:-/etc/ssl/pastepoint} directory with cert.pem and key.pem files"
        echo "Use generate-certs.sh script to generate self-signed certificates for development or provide your own for production."
        echo "Exiting..."
        exit 1
      fi
      echo "Certificates exist, continuing..."
      '
    volumes:
      - ${CERT_PATH:-/etc/ssl/pastepoint}:/etc/ssl/${CERT_MOUNT:-pastepoint}:ro
    restart: "no"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        RUST_BUILD_MODE: ${RUST_BUILD_MODE}
    ports:
      - "9000:9000"
    environment:
      - RUN_ENV=${SERVER_ENV:-production}
    volumes:
      - ${CERT_PATH:-/etc/ssl/pastepoint}:/etc/ssl/${CERT_MOUNT:-pastepoint}:ro
    depends_on:
      cert-checker:
        condition: service_completed_successfully
    restart: always

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        NPM_BUILD_CONFIG: ${NPM_BUILD_CONFIG}
    environment:
      SERVER_NAME: ${SERVER_NAME:-pastepoint.com www.pastepoint.com}
      SSL_CERT_PATH: ${SSL_CERT_PATH:-/etc/ssl/pastepoint/cert.pem}
      SSL_CERT_KEY_PATH: ${SSL_CERT_KEY_PATH:-/etc/ssl/pastepoint/key.pem}
    ports:
      - "443:443"
    volumes:
      - ${CERT_PATH:-/etc/ssl/pastepoint}:/etc/ssl/${CERT_MOUNT:-pastepoint}:ro
    depends_on:
      server:
        condition: service_started
    restart: always
