volumes:
  ssl-certs:

services:
  certs-generator:
    image: alpine
    entrypoint: /bin/sh -c "apk add --no-cache openssl && /usr/local/bin/generate-certs.sh"
    volumes:
      - ssl-certs:/etc/ssl/certs
      - ./scripts/generate-certs.sh:/usr/local/bin/generate-certs.sh:ro
    restart: "no"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9000:9000"
    environment:
      RUST_LOG: "info"
      RUN_ENV: "production"
    volumes:
      - ssl-certs:/etc/ssl/certs
    depends_on:
      certs-generator:
        condition: service_completed_successfully
    restart: always

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "443:443"
    depends_on:
      server:
        condition: service_started
    volumes:
      - ssl-certs:/etc/ssl/certs
    restart: always
