[server]
bind_address = "0.0.0.0:9000"
key_file_path = "/etc/ssl/pastepoint/key.pem"
cert_file_path = "/etc/ssl/pastepoint/cert.pem"
auto_join = true
rate_limit_per_second = 50
rate_limit_burst_size = 100
log_level = "info"
