name: Angular CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and Test Angular Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Lint and Format
        working-directory: client
        run: |
          npm run lint
          npm run format

      - name: Production Build
        working-directory: client
        run: npm run build --configuration=production

      - name: Run Tests with Coverage
        working-directory: client
        run: npm run test:coverage:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./client/coverage/
          flags: angular
          name: angular-coverage
          fail_ci_if_error: false
          verbose: true
