name: Angular CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and Test Angular Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Lint and Format
        working-directory: client
        run: |
          npm run lint
          npm run format

# Uncomment if you want to include a test step
#      - name: Run Tests
#        working-directory: client
#        run: npm test -- --watch=false --browsers=ChromeHeadless

# Uncomment if you want to include a security audit step
#      - name: Security Audit
#        working-directory: client
#        run: npm audit

      - name: Production Build
        working-directory: client
        run: npm run build --configuration=production

# Uncomment if you want to upload the release artifact
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        if: success() && github.ref == 'refs/heads/main'
#        with:
#          name: angular-dist
#          path: client/dist
