name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-08-29
          override: true
          components: rustfmt, clippy

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target  # Cache build artifacts for the server project
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('server/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-

      - name: Check code formatting
        working-directory: server
        run: cargo fmt -- --check

      - name: Run Clippy
        working-directory: server
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        working-directory: server
        run: cargo test --all --verbose

      - name: Build the Rust project
        working-directory: server
        run: cargo build --release --verbose
